/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2017-11-30 09:17:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset = \"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        <meta name=\"description\" content=\"\">\r\n");
      out.write("        <meta name=\"author\" content=\"\">\r\n");
      out.write("        <title>OTO CAFE</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/custom.css\">\r\n");
      out.write("   \t\t\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <image class=\"img-responsive center-block img-rounded\" src = \"images/main_banner.jpg\">\r\n");
      out.write("            <form class=\"form-signin\" method=\"post\" action=\"managerInsert\" onsubmit=\"return checkPw()\">\r\n");
      out.write("\t            <div class=\"form-subject\">회원가입</div>\r\n");
      out.write("                <hr class=\"form-hr\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"row form-join\">\r\n");
      out.write("                    <div class=\"col-xs-1\"></div>\r\n");
      out.write("                    <label for=\"id\" class=\"form-label col-xs-4\" style=\"font-size:20px;\">아이디 : </label>\r\n");
      out.write("                    <div class=\"col-xs-1\"></div>\r\n");
      out.write("                    <input type=\"text\" id=\"id\" name=\"id\" class=\"form-input col-xs-4\" data-toggle=\"popover\"  required autofocus>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- <button class=\"btn btn-lg btn-default col-xs-2 form-btn2\" id=\"duplication\">중복확인</button> -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row form-join\">\r\n");
      out.write("                    <div class=\"col-xs-1\"></div>\r\n");
      out.write("                    <label for=\"password\" class=\"form-label col-xs-4\" style=\"font-size:20px;\">비밀번호 : </label>\r\n");
      out.write("                    <div class=\"col-xs-1\"></div>\r\n");
      out.write("                    <input type=\"password\" id=\"pw\" name=\"pw\" class=\"form-input col-xs-4\"  required >\r\n");
      out.write("                    <div class=\"col-xs-1\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row form-join\">\r\n");
      out.write("                    <div class=\"col-xs-1\"></div>\r\n");
      out.write("                    <label for=\"checkId\" class=\"form-label col-xs-4\" style=\"font-size:20px;\">비밀번호 확인 : </label>\r\n");
      out.write("                    <div class=\"col-xs-1\"></div>\r\n");
      out.write("                    <input type=\"password\" id=\"pw_check\" class=\"form-input col-xs-4\"  required >\r\n");
      out.write("                    <div class=\"col-xs-1\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row form-join\">\r\n");
      out.write("                    <div class=\"col-xs-1\"></div>\r\n");
      out.write("                    <label for=\"name\" class=\"form-label col-xs-4\" style=\"font-size:20px;\">이름 : </label>\r\n");
      out.write("                    <div class=\"col-xs-1\"></div>\r\n");
      out.write("                    <input type=\"test\" id=\"name\" name=\"name\" class=\"form-input col-xs-4\"  required >\r\n");
      out.write("                    <div class=\"col-xs-1\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row form-join\">\r\n");
      out.write("                    <div class=\"col-xs-1\"></div>\r\n");
      out.write("                    <label for=\"email\" class=\"form-label col-xs-4\" style=\"font-size:20px;\">이메일 : </label>\r\n");
      out.write("                    <div class=\"col-xs-1\"></div>\r\n");
      out.write("                    <input type=\"email\" id=\"email\" name =\"email\" class=\"form-input col-xs-4\"  required >\r\n");
      out.write("                    <div class=\"col-xs-1\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row form-join\">\r\n");
      out.write("                    <div class=\"col-xs-1\"></div>\r\n");
      out.write("                    <label for=\"phone\" class=\"form-label col-xs-4\" style=\"font-size:20px;\">전화번호 : </label>\r\n");
      out.write("                    <div class=\"col-xs-1\"></div>\r\n");
      out.write("                    <input type=\"tel\" id=\"phone\" name=\"phone\" class=\"form-input col-xs-4\"  required >\r\n");
      out.write("                    <div class=\"col-xs-1\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row form-join\">\r\n");
      out.write("                    <div class=\"col-xs-1\"></div>\r\n");
      out.write("                    <label for=\"birth\" class=\"form-label col-xs-4\" style=\"font-size:20px;\">생년월일 : </label>\r\n");
      out.write("                    <div class=\"col-xs-1\"></div>\r\n");
      out.write("                    <input type=\"date\" id=\"birth\" name=\"birth\" class=\"form-input col-xs-4\"  required >\r\n");
      out.write("                    <div class=\"col-xs-1\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row form-join\">\r\n");
      out.write("                    <div class=\"col-xs-1\"></div>\r\n");
      out.write("                    <label for=\"gender\" class=\"form-label col-xs-4\" style=\"font-size:20px;\">성별 : </label>\r\n");
      out.write("                    <div class=\"col-xs-1\"></div>\r\n");
      out.write("                    <select class=\"form-input col-xs-4\" id=\"gender\" name=\"gender\" required>\r\n");
      out.write("                        <option value=\"남자\">남자</option>\r\n");
      out.write("                        <option valut=\"여자\">여자</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <div class=\"col-xs-1\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <hr class=\"form-hr\">\r\n");
      out.write("                <!--div class=\"checkbox\">\r\n");
      out.write("                    <label>\r\n");
      out.write("                        <input type=\"checkbox\" value=\"remember-me\"> Remember me\r\n");
      out.write("                    </label>\r\n");
      out.write("                </div-->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"center-block row form-btn\">\r\n");
      out.write("                    <div class=\"col-xs-2\"></div>\r\n");
      out.write("                    <button class=\"btn btn-lg btn-default col-xs-3\" type=\"submit\">회원가입</button>\r\n");
      out.write("                    <div class=\"col-xs-2\"></div>\r\n");
      out.write("                    <button class=\"btn btn-lg btn-default col-xs-3\" type=\"button\" onclick=\"location.href='/jspweb/'\">취소</button>\r\n");
      out.write("                    <div class=\"col-xs-2\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script src= \"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"js/bootstrap.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("        \r\n");
      out.write("        $(document).ready(function(){\r\n");
      out.write("            //$(\"#id\").keyup(idCheck);\r\n");
      out.write("            //$(\"#id\").focus(idCheck);\r\n");
      out.write("            //$(\"#id\").popover(\"destroy\");\r\n");
      out.write("            $(\"#id\").on('keyup focus', function(){\r\n");
      out.write("            \tconsole.log($(\"#id\").val());\r\n");
      out.write("            \tvar e = $(this);\r\n");
      out.write("            \tvar data;\r\n");
      out.write("            \tif($(\"#id\").val()){\r\n");
      out.write("\t                var query = {id:$(\"#id\").val()};\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t                        url : \"join/idCheck\",\r\n");
      out.write("\t                        type : \"post\",\r\n");
      out.write("\t                        data : query,\r\n");
      out.write("\t                        success : function(data) {\r\n");
      out.write("\t                        \t\r\n");
      out.write("\t                            if(data == 1){\r\n");
      out.write("\t                            \t/*$(\"#id\").popover('destroy').popover({\r\n");
      out.write("\t                            \t\tcontent : \"이 아이디를 사용할 수 없습니다.\",\r\n");
      out.write("\t                            \t\tplacement : \"right\"\r\n");
      out.write("\t                            \t});*/\r\n");
      out.write("\t                            \tdata = \"이 아이디를 사용할 수 없습니다.\";\r\n");
      out.write("\t                            \t\r\n");
      out.write("\t                            \te.css(\"border-color\", '#f96039');\r\n");
      out.write("\t                            \tconsole.log(\"1\");\r\n");
      out.write("\t                            } else if(data == -1){\r\n");
      out.write("\t                            \t/*$(\"#id\").popover('destroy').popover({\r\n");
      out.write("\t                            \t\tcontent : \"이 아이디를 사용할 수 있습니다.\",\r\n");
      out.write("\t                            \t\tplacement : \"right\"\r\n");
      out.write("\t                            \t});*/\r\n");
      out.write("\t                            \tdata = \"이 아이디를 사용할 수 있습니다.\";\r\n");
      out.write("\t                            \t\r\n");
      out.write("\t                            \te.css(\"border-color\", '');\r\n");
      out.write("\t                            \tconsole.log(\"2\");\r\n");
      out.write("\t                            }\r\n");
      out.write("\t                            \r\n");
      out.write("\t                            var popover = e.attr('data-content', data).data('bs.popover');\r\n");
      out.write("\t                            popover.$tip.addClass(popover.options.placement);\r\n");
      out.write("\t                            \r\n");
      out.write("\t                            e.popover({\r\n");
      out.write("\t                            \ttrigger: 'manual',\r\n");
      out.write("                            \t\tcontent : data,\r\n");
      out.write("                            \t\tplacement : \"right\"\r\n");
      out.write("                            \t}).popover('show');\r\n");
      out.write("\t                            \r\n");
      out.write("\t                            \r\n");
      out.write("\t                            //popover.setCotent();\r\n");
      out.write("\t                            //$(\"#id\").popover('show');\r\n");
      out.write("\t                           // console.log(\"3\");\r\n");
      out.write("\t                        }\r\n");
      out.write("\t                    });\r\n");
      out.write("                } else{\r\n");
      out.write("                \tconsole.log(\"4\");\r\n");
      out.write("                \tdata = \"아이디를 입력해주세요.\";\r\n");
      out.write("                \te.popover({\r\n");
      out.write("                \t\ttrigger: 'manual',\r\n");
      out.write("                \t\tcontent : data,\r\n");
      out.write("                \t\tplacement : \"right\"\r\n");
      out.write("                \t}).popover('show');\r\n");
      out.write("                \tvar popover = e.attr('data-content', data).data('bs.popover');\r\n");
      out.write("               \t \tpopover.$tip.addClass(popover.options.placement);\r\n");
      out.write("               \t \t\r\n");
      out.write("               \t \te.popover('show');\r\n");
      out.write("                \t\r\n");
      out.write("                \t\r\n");
      out.write("                \t\r\n");
      out.write("                \t \r\n");
      out.write("                     //popover.setCotent();\r\n");
      out.write("                \t/*$(\"#id\").popover({\r\n");
      out.write("                \t\ttrigger: 'manual',\r\n");
      out.write("                \t\tcontent : \"이 아이디를 입력해주세요.\",\r\n");
      out.write("                \t\tplacement : \"right\"\r\n");
      out.write("                \t}).popover('show');*/\r\n");
      out.write("                    //$(\"#id\").popover('show');\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("            /*$(\"#id\").blur(function(){\r\n");
      out.write("        \t\t$(this).popover('destroy');\r\n");
      out.write("        \t});*/\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("\t        function checkPw(){\r\n");
      out.write("\t            var pw = document.getElementById(\"pw\").value;\r\n");
      out.write("\t            var checkPw = document.getElementById(\"pw_check\").value;\r\n");
      out.write("\t\r\n");
      out.write("\t            if(pw != checkPw)\r\n");
      out.write("\t            {\r\n");
      out.write("\t                alert(\"비밀번호를 확인해주세요.\");\r\n");
      out.write("\r\n");
      out.write("                    document.getElementById(\"pw\").value = \"\";\r\n");
      out.write("                    document.getElementById(\"pw_check\").value = \"\";\r\n");
      out.write("\t                return false;\r\n");
      out.write("\t            }\r\n");
      out.write("\t\r\n");
      out.write("\t        }\r\n");
      out.write("\t        \r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("\t        \r\n");
      out.write("        \r\n");
      out.write("        </script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
