/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2017-12-16 17:22:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class manList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/workspace/apache-tomcat-9.0.0.M26/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("file:/E:/workspace/apache-tomcat-9.0.0.M26/lib/jstl-1.2.jar", Long.valueOf(1504193458445L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset = \"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        <meta name=\"description\" content=\"\">\r\n");
      out.write("        <meta name=\"author\" content=\"\">\r\n");
      out.write("        <title>OTO CAFE</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/dashboard.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/custom.css\">\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("    \t<nav class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("          <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">\r\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"#\">OTO CAFE</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("          <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("            <li><a href=\"manOrder\">주문목록</a></li>\r\n");
      out.write("            <li><a href=\"manList\">상품리스트</a></li>\r\n");
      out.write("            <li><a href=\"manSeat\">좌석관리</a></li>\r\n");
      out.write("            <li><a href=\"manUser\">회원관리</a></li>\r\n");
      out.write("            <li><a href=\"manStock\">재고관리</a></li>\r\n");
      out.write("            <li><a href=\"manProfit\">판매실적</a></li>\r\n");
      out.write("            <li><a href=\"/jspweb/\">로그아웃</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-sm-3 col-md-2 sidebar\">\r\n");
      out.write("          <ul class=\"nav nav-sidebar form-left-nav\">\r\n");
      out.write("            <li><a href=\"manOrder\">주문목록</a></li>\r\n");
      out.write("            <li class=\"active\"><a href=\"manList\">상품리스트<span class=\"sr-only\">(current)</span></a></li>\r\n");
      out.write("            <li><a href=\"manSeat\">좌석관리</a></li>\r\n");
      out.write("            <li><a href=\"manUser\">회원관리</a></li>\r\n");
      out.write("            <li><a href=\"manStock\">재고관리</a></li>\r\n");
      out.write("            <li><a href=\"manProfit\">판매실적</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main\">\r\n");
      out.write("          <image class=\"img-responsive center-block img-rounded\" src = \"images/main_banner.jpg\">\r\n");
      out.write("            <div class=\"form-subject\">\r\n");
      out.write("                상품리스트\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr class=\"form-hr\">\r\n");
      out.write("          \r\n");
      out.write("          <div role=\"tabpanel\"> \r\n");
      out.write("              \r\n");
      out.write("\t          <ul class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("\t\t\t    <li role=\"presentation\" class=\"active\"><a href=\"#coffee\" id=\"coffee-tab\" aria-controls=\"coffee\" role=\"tab\" data-toggle=\"tab\" class=\"custom-tab\">커피</a></li>\r\n");
      out.write("\t\t\t    <li role=\"presentation\"><a href=\"#beverage\" id=\"deverage-tab\" aria-controls=\"beverage\" role=\"tab\" data-toggle=\"tab\" class=\"custom-tab\">음료</a></li>\r\n");
      out.write("\t\t\t    <li role=\"presentation\"><a href=\"#dessert\" id=\"dessert-tab\" aria-controls=\"dessert\" role=\"tab\" data-toggle=\"tab\" class=\"custom-tab\">디저트</a></li>\r\n");
      out.write("\t\t\t  </ul>\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t          <div class = \"tab-content\">\r\n");
      out.write("\t          \r\n");
      out.write("\t          \t<div role=\"tabpanel\" class=\"tab-pane fade in active\" id=\"coffee\" aria-labelledby=\"coffee-tab\">\r\n");
      out.write("\t\t          <div class=\"table-responsive\">\r\n");
      out.write("\t\t            <table class=\"table table-striped\">\r\n");
      out.write("\t\t              <thead class=\"form-thead\">\r\n");
      out.write("\t\t                <tr>\r\n");
      out.write("\t\t                    <th>번호</th>\r\n");
      out.write("\t\t                    <th>이미지</th>\r\n");
      out.write("\t\t                    <th>품명</th>\r\n");
      out.write("\t\t                    <th>사이즈</th>\r\n");
      out.write("\t\t                    <th>가격</th>\r\n");
      out.write("\t\t                    <th>타입</th>\r\n");
      out.write("\t\t                    <th></th>\r\n");
      out.write("\t\t                </tr>\r\n");
      out.write("\t\t              </thead>\r\n");
      out.write("\t\t              <tbody>\r\n");
      out.write("\t              \t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t              </tbody>\r\n");
      out.write("\t\t            </table>\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t          </div> \r\n");
      out.write("               \t</div>\r\n");
      out.write("\t                \t\r\n");
      out.write("               \t<div role=\"tabpanel\" class=\"tab-pane fade\" id=\"beverage\" aria-labelledby=\"beverage-tab\">\r\n");
      out.write("\t               \t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t            <table class=\"table table-striped\">\r\n");
      out.write("\t\t\t              <thead class=\"form-thead\">\r\n");
      out.write("\t\t\t                <tr>\r\n");
      out.write("\t\t\t                    <th>번호</th>\r\n");
      out.write("\t\t\t                    <th>이미지</th>\r\n");
      out.write("\t\t\t                    <th>품명</th>\r\n");
      out.write("\t\t\t                    <th>사이즈</th>\r\n");
      out.write("\t\t\t                    <th>가격</th>\r\n");
      out.write("\t\t\t                    <th>타입</th>\r\n");
      out.write("\t\t\t                    <th></th>\r\n");
      out.write("\t\t\t                </tr>\r\n");
      out.write("\t\t\t              </thead>\r\n");
      out.write("\t\t\t              <tbody>\r\n");
      out.write("\t\t                \t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t                </tbody>\r\n");
      out.write("\t\t            </table>\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t          </div> \r\n");
      out.write("               \t</div>\r\n");
      out.write("               \t\r\n");
      out.write("               \t<div role=\"tabpanel\" class=\"tab-pane fade\" id=\"dessert\" aria-labelledby=\"dessert-tab\">\r\n");
      out.write("\t               \t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t            <table class=\"table table-striped\">\r\n");
      out.write("\t\t\t              <thead class=\"form-thead\">\r\n");
      out.write("\t\t\t                <tr>\r\n");
      out.write("\t\t\t                    <th>번호</th>\r\n");
      out.write("\t\t\t                    <th>이미지</th>\r\n");
      out.write("\t\t\t                    <th>품명</th>\r\n");
      out.write("\t\t\t                    <th>사이즈</th>\r\n");
      out.write("\t\t\t                    <th>가격</th>\r\n");
      out.write("\t\t\t                    <th></th>\r\n");
      out.write("\t\t\t                </tr>\r\n");
      out.write("\t\t\t              </thead>\r\n");
      out.write("\t\t\t              <tbody>\r\n");
      out.write("\t\t                \t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t        \t</tbody>\r\n");
      out.write("\t\t            </table>\r\n");
      out.write("\t\t          </div> \r\n");
      out.write("               \t</div>\r\n");
      out.write("\t      \t</div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <button class=\"btn btn-default\" data-toggle=\"modal\" data-target=\"#myModal\" onclick=\"init()\">상품추가</button>\r\n");
      out.write("\t \r\n");
      out.write("          <!-- Modal -->\r\n");
      out.write("          <div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("              <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                  <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("                  <h4 class=\"modal-title\" id=\"myModalLabel\">상품 추가</h4>\r\n");
      out.write("                </div>\r\n");
      out.write("                <form method=\"post\" action=\"manList/productInsert\" enctype=\"multipart/form-data\">\r\n");
      out.write("                  <div class=\"modal-body\">\r\n");
      out.write("                    <div class=\"container-fluid\">\r\n");
      out.write("                      <div class=\"col-xs-4 modal-data\" id= \"image\">\r\n");
      out.write("                        <div id=\"image-div\" style=\"height: 100%; width: 100%\">\r\n");
      out.write("                          <img class=\"img-responsive img-rounded\" id=\"coffeImage\" style=\"width: 150px; height: 180px;\" src = \"images/no_image.jpg\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <input type='file' id='file' name='file' style=\"width:0; height: 0;\"/>\r\n");
      out.write("                        <button class=\"modal-btn btn btn-default\" id=\"btn-upload\" onfocus=\"this.blur();\">이미지 추가</button>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"col-xs-8 modal-data\">\r\n");
      out.write("                      \t<div class=\"row\" id =\"data\">\r\n");
      out.write("                          <label class =\"form-label col-xs-2 modal-label\">품명 :</label>\r\n");
      out.write("                          <input type=\"text\" id=\"name\" name=\"name\" class=\"form-input col-xs-3\"  required>\r\n");
      out.write("                          <label class =\"form-label col-xs-2 modal-label\">종류 :</label>\r\n");
      out.write("                          <select class = \"form-input col-xs-3\" id=\"kinds\" name=\"kinds\" onchange=\"change(this);\" required>\r\n");
      out.write("                          \t<option value = \"1\">커피</option>\r\n");
      out.write("                          \t<option value = \"2\">음료</option>\r\n");
      out.write("                          \t<option value = \"3\">디저트</option>\r\n");
      out.write("                          </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\" id =\"data\">\r\n");
      out.write("                          <label class =\"form-label col-xs-2 modal-label\">Size :</label>\r\n");
      out.write("                          <label class =\"form-label col-xs-2 modal-sizelabel\">Small</label>\r\n");
      out.write("                          <div class=\"col-xs-1\"></div>\r\n");
      out.write("                          <label class =\"form-label col-xs-2 modal-label\">가격 :</label>\r\n");
      out.write("\r\n");
      out.write("                          <input type=\"text\" id=\"sPrice\" name=\"sPrice\" class=\"form-input col-xs-3\"  required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\" id =\"data\">\r\n");
      out.write("                            <label class =\"form-label col-xs-2 modal-label\">Size :</label>\r\n");
      out.write("                            <label class =\"form-label col-xs-2 modal-sizelabel\">Regular</label>\r\n");
      out.write("                            <div class=\"col-xs-1\"></div>\r\n");
      out.write("                            <label class =\"form-label col-xs-2 modal-label\">가격 :</label>\r\n");
      out.write("  \r\n");
      out.write("                            <input type=\"text\" id=\"rPrice\" name=\"rPrice\"class=\"form-input col-xs-3\" required>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"row\" id =\"data\">\r\n");
      out.write("                              <label class =\"form-label col-xs-2 modal-label\">Size :</label>\r\n");
      out.write("                              <label class =\"form-label col-xs-2 modal-sizelabel\">Large</label>\r\n");
      out.write("                              <div class=\"col-xs-1\"></div>\r\n");
      out.write("                              <label class =\"form-label col-xs-2 modal-label\">가격 :</label>\r\n");
      out.write("    \r\n");
      out.write("                              <input type=\"text\" id=\"lPrice\" name=\"lPrice\" class=\"form-input col-xs-3\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        \t<div class=\"row\" id =\"data\">\r\n");
      out.write("                        \t\t<div class=\"btn-group col-xs-12\" data-toggle=\"buttons\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <label class=\"btn btn-default active col-xs-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    <input type=\"radio\" name=\"radioOptions\" id=\"radioOption1\" autocomplete=\"off\" value=\"H\" checked> HOT\r\n");
      out.write("\t\t\t\t\t\t\t\t  </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <label class=\"btn btn-default  col-xs-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    <input type=\"radio\" name=\"radioOptions\" id=\"radioOption2\" autocomplete=\"off\" value=\"C\"> ICE\r\n");
      out.write("\t\t\t\t\t\t\t\t  </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <label class=\"btn btn-default  col-xs-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    <input type=\"radio\" name=\"radioOptions\" id=\"radioOption3\" autocomplete=\"off\" value=\"HC\"> HOT&ICE\r\n");
      out.write("\t\t\t\t\t\t\t\t  </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"radioVal\" id=\"radioVal\" style=\"display:none;\" value=\"\">\r\n");
      out.write("                        \t</div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("                    <input type=\"text\" id=\"uuid\" name=\"uuid\" style=\"display:none;\" value=\"blank\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">등록</button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </form>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("        <script src= \"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("          \r\n");
      out.write("          var file;\r\n");
      out.write("\r\n");
      out.write("          $(document).ready(function(){\r\n");
      out.write("            var fileTarget = $(\"#file\");\r\n");
      out.write("            fileTarget.on(\"change\", function(){\r\n");
      out.write("\r\n");
      out.write("              ext = $(this).val().split('.').pop().toLowerCase(); //확장자\r\n");
      out.write("        \r\n");
      out.write("              //배열에 추출한 확장자가 존재하는지 체크\r\n");
      out.write("              if($.inArray(ext, ['gif', 'png', 'jpg', 'jpeg']) == -1) {\r\n");
      out.write("                resetImage();\r\n");
      out.write("                window.alert('이미지 파일이 아닙니다! (gif, png, jpg, jpeg 만 업로드 가능)');\r\n");
      out.write("              } else {\r\n");
      out.write("                file = fileTarget.prop(\"files\")[0];\r\n");
      out.write("                //console.log(file);\r\n");
      out.write("                //file.blobURL();\r\n");
      out.write("                blobURL = window.URL.createObjectURL(file);\r\n");
      out.write("                $('#coffeImage').attr('src', blobURL);\r\n");
      out.write("                $('#image-div').slideDown(); //업로드한 이미지 미리보기 \r\n");
      out.write("                $(this).slideUp(); //파일 양식 감춤\r\n");
      out.write("              }\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            $(\"input[name='radioOptions']\").on(\"change\", function(){\r\n");
      out.write("            \tvar val = $(this).val();\r\n");
      out.write("            \tconsole.log(\"change\" + val);\r\n");
      out.write("            \t$('#radioVal').val(val);\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            //var radio\r\n");
      out.write("          });\r\n");
      out.write("          \r\n");
      out.write("          $(function(){          \r\n");
      out.write("            $('#btn-upload').click(function(e){\r\n");
      out.write("              e.preventDefault();  \r\n");
      out.write("              $(\"#file\").click();             \r\n");
      out.write("            });                         \r\n");
      out.write("          });\r\n");
      out.write("\r\n");
      out.write("          function resetImage(){\r\n");
      out.write("            $('#coffeImage').attr('src', \"images/no_image.jpg\");\r\n");
      out.write("            $('#image-div').slideDown(); //업로드한 이미지 미리보기 \r\n");
      out.write("          }\r\n");
      out.write("          \r\n");
      out.write("          function resetData(){\r\n");
      out.write("        \t  $('#name').val(\"\");\r\n");
      out.write("        \t  $('#sPrice').val(\"\");\r\n");
      out.write("        \t  $('#rPrice').val(\"\");\r\n");
      out.write("        \t  $('#lPrice').val(\"\");\r\n");
      out.write("        \t  $('#uuid').val(\"blank\");\r\n");
      out.write("        \t  $('#kinds').val(\"1\").prop(\"selected\", true);\r\n");
      out.write("        \t  $('#radioVal').val(\"H\");\r\n");
      out.write("        \t  $('[data-toggle=\"buttons\"] :radio').prop('checked', false);\r\n");
      out.write("        \t   // Select all label elements within your toggle and remove the active class\r\n");
      out.write("        \t   $('[data-toggle=\"buttons\"] label').removeClass('active');\r\n");
      out.write("\r\n");
      out.write("        \t   // Set the first one as checked and selected\r\n");
      out.write("        \t   //$('[data-toggle=\"buttons\"] :radio:first').addClass('active');\r\n");
      out.write("        \t   // Do the same thing for the active indicator\r\n");
      out.write("        \t   $('[data-toggle=\"buttons\"] label:first').addClass('active');\r\n");
      out.write("        \t  //$(\"#input:radio[name=radioOptions]\").removeAttr(\"checked\");\r\n");
      out.write("        \t // $(\"input[name='radioOptions'][value='1']\").prop(\"checked\", true);\r\n");
      out.write("        \t  $(\"#radioOption1\").prop(\"checked\", true);\r\n");
      out.write("        \t   console.log($(\"input[name='radioOptions']:checked\").val());\r\n");
      out.write("          }\r\n");
      out.write("          \r\n");
      out.write("          function init(){\r\n");
      out.write("        \t  resetImage();\r\n");
      out.write("        \t  resetData();\r\n");
      out.write("          }\r\n");
      out.write("          \r\n");
      out.write("          function modalSetting(url, name, s, r, l, id, kinds, type){\r\n");
      out.write("        \t  \r\n");
      out.write("        \t$('#coffeImage').attr('src', url);\r\n");
      out.write("            $('#image-div').slideDown(); //업로드한 이미지 미리보기 \r\n");
      out.write("        \t$('#name').val(name);\r\n");
      out.write("        \t$('#sPrice').val(s);\r\n");
      out.write("        \t$('#rPrice').val(r);\r\n");
      out.write("        \t$('#lPrice').val(l);\r\n");
      out.write("        \t$('#uuid').val(id);\r\n");
      out.write("        \tconsole.log(kinds);\r\n");
      out.write("        \t$('#kinds').val(kinds).prop(\"selected\", true);\r\n");
      out.write("        \t$('#radioVal').val(type);\r\n");
      out.write("        \t$('[data-toggle=\"buttons\"] :radio').prop('checked', false);\r\n");
      out.write("        \t$('[data-toggle=\"buttons\"] label').removeClass('active');\r\n");
      out.write("\t\t\t\r\n");
      out.write("        \tconsole.log(type);\r\n");
      out.write("        \tconsole.log($('#radioVal').val());\r\n");
      out.write("        \tif(type == 'H'){\r\n");
      out.write("\t        \t$('[data-toggle=\"buttons\"] label:first').addClass('active');\r\n");
      out.write("\t        \t$(\"#radioOption1\").prop(\"checked\", true);\r\n");
      out.write("        \t} else if(type == 'C'){\r\n");
      out.write("        \t\t$('[data-toggle=\"buttons\"] label:first').next().addClass('active');\r\n");
      out.write("\t        \t$(\"#radioOption2\").prop(\"checked\", true);\r\n");
      out.write("        \t} else if(type == 'HC'){\r\n");
      out.write("        \t\t$('[data-toggle=\"buttons\"] label:first').next().next().addClass('active');\r\n");
      out.write("\t        \t$(\"#radioOption3\").prop(\"checked\", true);\r\n");
      out.write("        \t}\r\n");
      out.write("        \t console.log($(\"input[name='radioOptions']:checked\").val());\r\n");
      out.write("          }\r\n");
      out.write("          \r\n");
      out.write("          function change(elm){\r\n");
      out.write("        \t  if($(elm).val() == \"3\"){\r\n");
      out.write("        \t\t  $(\"#sPrice\").val(\"0\");\r\n");
      out.write("        \t\t  $(\"#sPrice\").attr(\"readOnly\", true);\r\n");
      out.write("        \t\t  $(\"#lPrice\").val(\"0\");\r\n");
      out.write("        \t\t  $(\"#lPrice\").attr(\"readOnly\", true);\r\n");
      out.write("        \t\t  $(\"#radioVal\").val(\"0\");\r\n");
      out.write("        \t\t  $('[data-toggle=\"buttons\"] :radio').attr(\"disabled\", true);\r\n");
      out.write("        \t\t  $('[data-toggle=\"buttons\"] label').attr(\"disabled\", true);\r\n");
      out.write("        \t  }\r\n");
      out.write("        \t  else{\r\n");
      out.write("        \t\t  $(\"#sPrice\").attr(\"readOnly\", false);\r\n");
      out.write("        \t\t  $(\"#lPrice\").attr(\"readOnly\", false);\r\n");
      out.write("        \t\t  $('[data-toggle=\"buttons\"] :radio').attr(\"disabled\", false);\r\n");
      out.write("        \t\t  $('[data-toggle=\"buttons\"] label').attr(\"disabled\", false);\r\n");
      out.write("        \t\t  $('#radioVal').val(\"1\");\r\n");
      out.write("            \t  $('[data-toggle=\"buttons\"] :radio').prop('checked', false);\r\n");
      out.write("            \t  $('[data-toggle=\"buttons\"] label').removeClass('active');\r\n");
      out.write("            \t  $('[data-toggle=\"buttons\"] label:first').addClass('active');\r\n");
      out.write("            \t  $(\"#radioOption1\").prop(\"checked\", true);\r\n");
      out.write("            \t   console.log($(\"input[name='radioOptions']:checked\").val());\r\n");
      out.write("        \t  }\r\n");
      out.write("        \t  \r\n");
      out.write("          }\r\n");
      out.write("        </script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/manList.jsp(88,17) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("row");
      // /WEB-INF/views/manList.jsp(88,17) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/manList.jsp(88,17) '${cList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${cList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t                <tr>\r\n");
            out.write("\t\t                \t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t                \t<td>\r\n");
            out.write("\t\t                \t\t<img class=\"img-responsive img-rounded\" style=\"width: 50px; height: 60px;\" src = ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.imageURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(">\r\n");
            out.write("\t\t                \t</td>\r\n");
            out.write("\t\t                \t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t                \t<td>small<br>regular<br>large</td>\r\n");
            out.write("\t\t                \t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.sPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("<br>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.rPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("<br>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.lPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t                \t");
            if (_jspx_meth_c_005fchoose_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t                \t<td>\r\n");
            out.write("\t\t                \t\t<form method=\"post\" action=\"manList/delete\" >\r\n");
            out.write("\t\t\t               \t\t\t<button type=\"button\" onclick=\"modalSetting('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.imageURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.sPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.rPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.lPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', 1, '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');\" class=\"btn btn-default\" data-toggle=\"modal\" data-target=\"#myModal\">수정</button>\r\n");
            out.write("\t\t\t               \t\t\t<input type=\"text\" name=\"delId\" style=\"display:none;\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("\t\t\t               \t\t\t<input type=\"text\" name=\"delkinds\" style=\"display:none;\" value=\"1\">\r\n");
            out.write("\t\t\t                     \t<button type=\"submit\" class=\"btn btn-default\">삭제</button>\r\n");
            out.write("\t\t                     \t</form>\r\n");
            out.write("\t\t                    </td>  \r\n");
            out.write("\t\t                </tr>\r\n");
            out.write("\t\t                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t                \t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t                \t\t");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t                \t\t");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t                \t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/manList.jsp(98,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.type eq 'H'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t                \t\t\t<td>HOT</td>\r\n");
          out.write("\t\t                \t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/manList.jsp(101,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.type eq 'C'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t                \t\t\t<td>ICE</td>\r\n");
          out.write("\t\t                \t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/manList.jsp(104,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.type eq 'HC'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t                \t\t\t<td>HOT & ICE</td>\r\n");
          out.write("\t\t                \t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/manList.jsp(139,19) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("row");
      // /WEB-INF/views/manList.jsp(139,19) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/manList.jsp(139,19) '${bList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${bList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t                <tr>\r\n");
            out.write("\t\t\t\t                \t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t                \t<td>\r\n");
            out.write("\t\t\t\t                \t\t<img class=\"img-responsive img-rounded\" style=\"width: 50px; height: 60px;\" src = ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.imageURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(">\r\n");
            out.write("\t\t\t\t                \t</td>\r\n");
            out.write("\t\t\t\t                \t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t                \t<td>small<br>regular<br>large</td>\r\n");
            out.write("\t\t\t\t                \t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.sPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("<br>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.rPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("<br>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.lPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t                \t");
            if (_jspx_meth_c_005fchoose_005f1(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t                \t<td>\r\n");
            out.write("\t\t\t\t                \t\t<form method=\"post\" action=\"manList/delete\" >\r\n");
            out.write("\t\t\t\t\t               \t\t\t<button type=\"button\" onclick=\"modalSetting('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.imageURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.sPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.rPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.lPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', 2, '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');\" class=\"btn btn-default\" data-toggle=\"modal\" data-target=\"#myModal\">수정</button>\r\n");
            out.write("\t\t\t\t\t               \t\t\t<input type=\"text\" name=\"delId\" style=\"display:none;\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("\t\t\t\t\t               \t\t\t<input type=\"text\" name=\"delkinds\" style=\"display:none;\" value=\"2\">\r\n");
            out.write("\t\t\t\t\t                     \t<button type=\"submit\" class=\"btn btn-default\">삭제</button>\r\n");
            out.write("\t\t\t\t                     \t</form>\r\n");
            out.write("\t\t\t\t                    </td>  \r\n");
            out.write("\t\t\t\t                </tr>\r\n");
            out.write("\t\t\t                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t                \t\t");
          if (_jspx_meth_c_005fwhen_005f3(_jspx_th_c_005fchoose_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t                \t\t");
          if (_jspx_meth_c_005fwhen_005f4(_jspx_th_c_005fchoose_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t                \t\t");
          if (_jspx_meth_c_005fwhen_005f5(_jspx_th_c_005fchoose_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t                \t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f3 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f3_reused = false;
    try {
      _jspx_th_c_005fwhen_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/views/manList.jsp(149,22) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.type eq 'H'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f3 = _jspx_th_c_005fwhen_005f3.doStartTag();
      if (_jspx_eval_c_005fwhen_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t                \t\t\t<td>HOT</td>\r\n");
          out.write("\t\t\t\t\t                \t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f3);
      _jspx_th_c_005fwhen_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f4 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f4_reused = false;
    try {
      _jspx_th_c_005fwhen_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/views/manList.jsp(152,23) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.type eq 'C'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f4 = _jspx_th_c_005fwhen_005f4.doStartTag();
      if (_jspx_eval_c_005fwhen_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t                \t\t\t<td>ICE</td>\r\n");
          out.write("\t\t\t\t\t                \t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f4);
      _jspx_th_c_005fwhen_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f5 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f5_reused = false;
    try {
      _jspx_th_c_005fwhen_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/views/manList.jsp(155,23) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.type eq 'HC'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f5 = _jspx_th_c_005fwhen_005f5.doStartTag();
      if (_jspx_eval_c_005fwhen_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t                \t\t\t<td>HOT & ICE</td>\r\n");
          out.write("\t\t\t\t\t                \t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f5);
      _jspx_th_c_005fwhen_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /WEB-INF/views/manList.jsp(189,19) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("row");
      // /WEB-INF/views/manList.jsp(189,19) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/manList.jsp(189,19) '${dList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${dList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t                <tr>\r\n");
            out.write("\t\t\t\t                \t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t                \t<td>\r\n");
            out.write("\t\t\t\t                \t\t<img class=\"img-responsive img-rounded\" style=\"width: 50px; height: 60px;\" src = ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.imageURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(">\r\n");
            out.write("\t\t\t\t                \t</td>\r\n");
            out.write("\t\t\t\t                \t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t                \t<td>regular</td>\r\n");
            out.write("\t\t\t\t                \t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.rPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t                \t<td>\r\n");
            out.write("\t\t\t\t                \t\t<form method=\"post\" action=\"manList/delete\" >\r\n");
            out.write("\t\t\t\t\t               \t\t\t<button type=\"button\" onclick=\"modalSetting('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.imageURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.sPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.rPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.lPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', 3, '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');\" class=\"btn btn-default\" data-toggle=\"modal\" data-target=\"#myModal\">수정</button>\r\n");
            out.write("\t\t\t\t\t               \t\t\t<input type=\"text\" name=\"delId\" style=\"display:none;\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("\t\t\t\t\t               \t\t\t<input type=\"text\" name=\"delkinds\" style=\"display:none;\" value=\"3\">\r\n");
            out.write("\t\t\t\t\t                     \t<button type=\"submit\" class=\"btn btn-default\">삭제</button>\r\n");
            out.write("\t\t\t\t                     \t</form>\r\n");
            out.write("\t\t\t\t                    </td>  \r\n");
            out.write("\t\t\t\t                </tr>\r\n");
            out.write("\t\t\t                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }
}
