/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2017-12-16 17:26:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class manProfit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/workspace/apache-tomcat-9.0.0.M26/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("file:/E:/workspace/apache-tomcat-9.0.0.M26/lib/jstl-1.2.jar", Long.valueOf(1504193458445L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset = \"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        <meta name=\"description\" content=\"\">\r\n");
      out.write("        <meta name=\"author\" content=\"\">\r\n");
      out.write("        <title>OTO CAFE</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/dashboard.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/custom.css\">\r\n");
      out.write("        <link class=\"include\" rel=\"stylesheet\" href=\"css/jquery.jqplot.css\">\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("    \t<nav class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("          <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">\r\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"#\">OTO CAFE</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("          <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("            <li><a href=\"manOrder\">주문목록</a></li>\r\n");
      out.write("            <li><a href=\"manList\">상품리스트</a></li>\r\n");
      out.write("            <li><a href=\"manSeat\">좌석관리</a></li>\r\n");
      out.write("            <li><a href=\"manUser\">회원관리</a></li>\r\n");
      out.write("            <li><a href=\"manStock\">재고관리</a></li>\r\n");
      out.write("            <li><a href=\"manProfit\">판매실적</a></li>\r\n");
      out.write("            <li><a href=\"/jspweb/\">로그아웃</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-sm-3 col-md-2 sidebar\">\r\n");
      out.write("          <ul class=\"nav nav-sidebar form-left-nav\">\r\n");
      out.write("            <li><a href=\"manOrder\">주문목록</a></li>\r\n");
      out.write("            <li><a href=\"manList\">상품리스트</a></li>\r\n");
      out.write("            <li><a href=\"manSeat\">좌석관리</a></li>\r\n");
      out.write("            <li><a href=\"manUser\">회원관리</a></li>\r\n");
      out.write("            <li><a href=\"manStock\">재고관리</a></li>\r\n");
      out.write("            <li  class=\"active\"><a href=\"manProfit\">판매실적<span class=\"sr-only\">(current)</span></a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main\">\r\n");
      out.write("          <image class=\"img-responsive center-block img-rounded\" src = \"images/main_banner.jpg\">\r\n");
      out.write("            <div class=\"form-subject\">\r\n");
      out.write("                판매실적\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr class=\"form-hr\">\r\n");
      out.write("         \t\r\n");
      out.write("         <div role=\"tabpanel\" id=\"tabs\"> \r\n");
      out.write("            \r\n");
      out.write("          <ul class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("            <li role=\"presentation\" class=\"active\"><a href=\"#month\" id=\"month-tab\" aria-controls=\"month\" role=\"tab\" data-toggle=\"tab\" class=\"custom-tab\">월별</a></li>\r\n");
      out.write("            <li role=\"presentation\"><a href=\"#age\" id=\"age-tab\" aria-controls=\"age\" role=\"tab\" data-toggle=\"tab\" class=\"custom-tab\">연령별 선호도</a></li>\r\n");
      out.write("            <li role=\"presentation\"><a href=\"#gender\" id=\"gender-tab\" aria-controls=\"gender\" role=\"tab\" data-toggle=\"tab\" class=\"custom-tab\">성별 선호도</a></li>\r\n");
      out.write("            <li role=\"presentation\"><a href=\"#menu\" id=\"menu-tab\" aria-controls=\"menu\" role=\"tab\" data-toggle=\"tab\" class=\"custom-tab\">메뉴별 선호도</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("      \r\n");
      out.write("          <div class = \"tab-content\">\r\n");
      out.write("            <div role=\"tabpanel\" class=\"tab-pane fade in active\" id=\"month\" aria-labelledby=\"month-tab\">\r\n");
      out.write("              <div id=\"graph\" style=\"width: 90%; height:400px;\"></div> \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div role=\"tabpanel\" class=\"tab-pane fade active\" id=\"age\" aria-labelledby=\"age-tab\">\r\n");
      out.write("            \t<div role=\"tabpanel\" id=\"tabs\">\r\n");
      out.write("\t\t          <ul class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("\t\t            <li role=\"presentation\" class=\"active\"><a href=\"#age10\" id=\"age10-tab\" aria-controls=\"age10\" role=\"tab\" data-toggle=\"tab\" class=\"custom-tab\">10대</a></li>\r\n");
      out.write("\t\t            <li role=\"presentation\"><a href=\"#age20\" id=\"age20-tab\" aria-controls=\"age20\" role=\"tab\" data-toggle=\"tab\" class=\"custom-tab\">20대</a></li>\r\n");
      out.write("\t\t            <li role=\"presentation\"><a href=\"#age30\" id=\"age30-tab\" aria-controls=\"age30\" role=\"tab\" data-toggle=\"tab\" class=\"custom-tab\">30대</a></li>\r\n");
      out.write("\t\t            <li role=\"presentation\"><a href=\"#age40\" id=\"age40-tab\" aria-controls=\"age40\" role=\"tab\" data-toggle=\"tab\" class=\"custom-tab\">40대</a></li>\r\n");
      out.write("\t\t            <li role=\"presentation\"><a href=\"#ageEtc\" id=\"ageEtc-tab\" aria-controls=\"ageEtc\" role=\"tab\" data-toggle=\"tab\" class=\"custom-tab\">기타</a></li>\r\n");
      out.write("\t\t          </ul>\r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t          <div class = \"tab-content\">\r\n");
      out.write("\t\t            <div role=\"tabpanel\" class=\"tab-pane fade in active\" id=\"age10\" aria-labelledby=\"age10-tab\">\r\n");
      out.write("\t\t               <div id=\"age10Plot\" style=\"width: 90%; height:400px;\"></div> \r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t            <div role=\"tabpanel\" class=\"tab-pane fade active\" id=\"age20\" aria-labelledby=\"age20-tab\">\r\n");
      out.write("\t\t               <div id=\"age20Plot\" style=\"width: 90%; height:400px;\"></div>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t            <div role=\"tabpanel\" class=\"tab-pane fade active\" id=\"age30\" aria-labelledby=\"age30-tab\">\r\n");
      out.write("\t\t               <div id=\"age30Plot\" style=\"width: 90%; height:400px;\"></div>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t            <div role=\"tabpanel\" class=\"tab-pane fade active\" id=\"age40\" aria-labelledby=\"age40-tab\">\r\n");
      out.write("\t\t               <div id=\"age40Plot\" style=\"width: 90%; height:400px;\"></div>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t            <div role=\"tabpanel\" class=\"tab-pane fade active\" id=\"ageEtc\" aria-labelledby=\"ageEtc-tab\">\r\n");
      out.write("\t\t               <div id=\"ageEtcPlot\" style=\"width: 90%; height:400px;\"></div>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div role=\"tabpanel\" class=\"tab-pane fade active\" id=\"gender\" aria-labelledby=\"gender-tab\">\r\n");
      out.write("              <div role=\"tabpanel\" id=\"tabs\">\r\n");
      out.write("\t\t          <ul class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("\t\t            <li role=\"presentation\" class=\"active\"><a href=\"#male\" id=\"male-tab\" aria-controls=\"male\" role=\"tab\" data-toggle=\"tab\" class=\"custom-tab\">남자</a></li>\r\n");
      out.write("\t\t            <li role=\"presentation\"><a href=\"#female\" id=\"female-tab\" aria-controls=\"female\" role=\"tab\" data-toggle=\"tab\" class=\"custom-tab\">여자</a></li>\r\n");
      out.write("\t\t          </ul>\r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t          <div class = \"tab-content\">\r\n");
      out.write("\t\t            <div role=\"tabpanel\" class=\"tab-pane fade in active\" id=\"male\" aria-labelledby=\"male-tab\">\r\n");
      out.write("\t\t               <div id=\"malePlot\" style=\"width: 90%; height:400px;\"></div> \r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t            <div role=\"tabpanel\" class=\"tab-pane fade active\" id=\"female\" aria-labelledby=\"female-tab\">\r\n");
      out.write("\t\t               <div id=\"femalePlot\" style=\"width: 90%; height:400px;\"></div>\r\n");
      out.write("\t\t            </div>            \r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div role=\"tabpanel\" class=\"tab-pane fade active\" id=\"menu\" aria-labelledby=\"menu-tab\">\r\n");
      out.write("              <div role=\"tabpanel\" id=\"tabs\">\r\n");
      out.write("\t\t          <ul class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("\t\t            <li role=\"presentation\" class=\"active\"><a href=\"#coffee\" id=\"coffee-tab\" aria-controls=\"coffee\" role=\"tab\" data-toggle=\"tab\" class=\"custom-tab\">커피</a></li>\r\n");
      out.write("\t\t            <li role=\"presentation\"><a href=\"#beverage\" id=\"beverage-tab\" aria-controls=\"beverage\" role=\"tab\" data-toggle=\"tab\" class=\"custom-tab\">음료</a></li>\r\n");
      out.write("\t\t            <li role=\"presentation\"><a href=\"#dessert\" id=\"dessert-tab\" aria-controls=\"dessert\" role=\"tab\" data-toggle=\"tab\" class=\"custom-tab\">디저트</a></li>\r\n");
      out.write("\t\t          </ul>\r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t          <div class = \"tab-content\">\r\n");
      out.write("\t\t            <div role=\"tabpanel\" class=\"tab-pane fade in active\" id=\"coffee\" aria-labelledby=\"coffee-tab\">\r\n");
      out.write("\t\t               <div id=\"coffeePlot\" style=\"width: 90%; height:400px;\"></div> \r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t            <div role=\"tabpanel\" class=\"tab-pane fade active\" id=\"beverage\" aria-labelledby=\"beverage-tab\">\r\n");
      out.write("\t\t               <div id=\"beveragePlot\" style=\"width: 90%; height:400px;\"></div>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t            <div role=\"tabpanel\" class=\"tab-pane fade active\" id=\"dessert\" aria-labelledby=\"dessert-tab\">\r\n");
      out.write("\t\t               <div id=\"dessertPlot\" style=\"width: 90%; height:400px;\"></div>\r\n");
      out.write("\t\t            </div>                      \r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\t\t        </div> \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("          \r\n");
      out.write("                \r\n");
      out.write("          </div>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("      \r\n");
      out.write("     \r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("    <script src= \"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/bootstrap.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery.jqplot.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery.jqplot.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/plugins/jqplot.categoryAxisRenderer.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/plugins/jqplot.barRenderer.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/plugins/jqplot.pieRenderer.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/plugins/jqplot.pointLabels.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    \tvar plot1;\r\n");
      out.write("    \tvar agePlot1;\r\n");
      out.write("    \tvar agePlot2;\r\n");
      out.write("    \tvar agePlot3;\r\n");
      out.write("    \tvar agePlot4;\r\n");
      out.write("    \tvar agePlot5;\r\n");
      out.write("    \tvar genderPlot1;\r\n");
      out.write("    \tvar genderPlot2;\r\n");
      out.write("    \tvar menuPlot1;\r\n");
      out.write("    \tvar menuPlot2;\r\n");
      out.write("    \tvar menuPlot3;\r\n");
      out.write("    \t\r\n");
      out.write("      $(document).ready(function(){\r\n");
      out.write("        $.jqplot.config.enablePlugins = true;\r\n");
      out.write("        \r\n");
      out.write("        var data1 = [];\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar average = 0;\r\n");
      out.write("\t\tfor(var i=0; i<data1.length; i++){\r\n");
      out.write("\t\t\taverage += parseInt(data1[i]);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tconsole.log(average);\r\n");
      out.write("\t\taverage = average/4;\r\n");
      out.write("\t\tconsole.log(average);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tconsole.log(data1);\r\n");
      out.write("        var ticks1 = ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'];\r\n");
      out.write("\r\n");
      out.write("        plot1 = $.jqplot('graph', [data1] , {\r\n");
      out.write("              title: '2017년 월별 수익',\r\n");
      out.write("              animate: !$.jqplot.use_excanvas,\r\n");
      out.write("              seriesDefaults:{\r\n");
      out.write("                  renderer:$.jqplot.BarRenderer,\r\n");
      out.write("                  pointLabels: { show: true },\r\n");
      out.write("                  rendererOptions: {\r\n");
      out.write("                      varyBarColor: true\r\n");
      out.write("                  }\r\n");
      out.write("              },\r\n");
      out.write("              axes: {\r\n");
      out.write("                xaxis: {\r\n");
      out.write("                  renderer: $.jqplot.CategoryAxisRenderer,\r\n");
      out.write("                  label: \"월별\",\r\n");
      out.write("                  ticks: ticks1\r\n");
      out.write("                },\r\n");
      out.write("                yaxis: {\r\n");
      out.write("                  label: \"수익\",\r\n");
      out.write("                  max : average,\r\n");
      out.write("                  min : 0\r\n");
      out.write("                }\r\n");
      out.write("              },\r\n");
      out.write("              highlighter: { show: false },\r\n");
      out.write("              seriesColors:['#7B93B4', '#F6A0AA', '#7BBD9D', '#DDF39E', '#FFDAA6',\r\n");
      out.write("            \t  '#A977B5', '#FFFFA6', '#6DA8A8', '#DA8DB3', '#8784BD']\r\n");
      out.write("            });      \r\n");
      out.write("          });\r\n");
      out.write("      \r\n");
      out.write("      $(document).ready(function(){\r\n");
      out.write("    \t  \r\n");
      out.write("    \t  var age10 = [];\r\n");
      out.write("    \t  var age20 = [];\r\n");
      out.write("    \t  var age30 = [];\r\n");
      out.write("    \t  var age40 = [];\r\n");
      out.write("    \t  var ageEtc = [];\r\n");
      out.write("    \t  \r\n");
      out.write("    \t  ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t  console.log(age10);\r\n");
      out.write("\t\t  //sortArr(age10);\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  ");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t  console.log(age20);\r\n");
      out.write("\t\t  //sortArr(age20);\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  ");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t  console.log(age30);\r\n");
      out.write("\t\t  //sortArr(age30);\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  ");
      if (_jspx_meth_c_005fforEach_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t  console.log(age40);\r\n");
      out.write("\t\t // sortArr(age40);\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  ");
      if (_jspx_meth_c_005fforEach_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t  console.log(ageEtc);\r\n");
      out.write("\t\t  //sortArr(ageEtc);\r\n");
      out.write("    \t  \r\n");
      out.write("    \t  agePlot1 = $.jqplot('age10Plot', [age10], {\r\n");
      out.write("    \t        gridPadding: {top:0, bottom:38, left:0, right:0},\r\n");
      out.write("    \t        seriesDefaults:{\r\n");
      out.write("\t  \t            renderer:$.jqplot.PieRenderer, \r\n");
      out.write("\t  \t            trendline:{ show:false }, \r\n");
      out.write("\t  \t            rendererOptions: { padding: 8, showDataLabels: true, sliceMargin:6, dataLabelFontSize:50 },\r\n");
      out.write("\t  \t        },\r\n");
      out.write("\t  \t        legend:{\r\n");
      out.write("\t  \t            show:true, \r\n");
      out.write("\t  \t            location:'w',\r\n");
      out.write("\t  \t            fontSize: 15\r\n");
      out.write("\t  \t        },\r\n");
      out.write("    \t        seriesColors:['#7B93B4', '#F6A0AA', '#7BBD9D', '#DDF39E', '#FFDAA6']\r\n");
      out.write("    \t    });\r\n");
      out.write("    \t  \r\n");
      out.write("    \t  agePlot2 = $.jqplot('age20Plot', [age20], {\r\n");
      out.write("\t  \t        gridPadding: {top:0, bottom:38, left:0, right:0},\r\n");
      out.write("\t  \t      seriesDefaults:{\r\n");
      out.write("\t  \t            renderer:$.jqplot.PieRenderer, \r\n");
      out.write("\t  \t            trendline:{ show:false }, \r\n");
      out.write("\t  \t            rendererOptions: { padding: 8, showDataLabels: true, sliceMargin:6, dataLabelFontSize:50 },\r\n");
      out.write("\t  \t        },\r\n");
      out.write("\t  \t        legend:{\r\n");
      out.write("\t  \t            show:true, \r\n");
      out.write("\t  \t            location:'w',\r\n");
      out.write("\t  \t            fontSize: 15\r\n");
      out.write("\t  \t        },\r\n");
      out.write("\t  \t      \tseriesColors:['#7B93B4', '#F6A0AA', '#7BBD9D', '#DDF39E', '#FFDAA6']\r\n");
      out.write("\t  \t    }); \r\n");
      out.write("    \t  \r\n");
      out.write("    \t  agePlot3 = $.jqplot('age30Plot', [age30], {\r\n");
      out.write("\t  \t        gridPadding: {top:0, bottom:38, left:0, right:0},\r\n");
      out.write("\t  \t      seriesDefaults:{\r\n");
      out.write("\t  \t            renderer:$.jqplot.PieRenderer, \r\n");
      out.write("\t  \t            trendline:{ show:false }, \r\n");
      out.write("\t  \t            rendererOptions: { padding: 8, showDataLabels: true, sliceMargin:6, dataLabelFontSize:50 },\r\n");
      out.write("\t  \t        },\r\n");
      out.write("\t  \t        legend:{\r\n");
      out.write("\t  \t            show:true, \r\n");
      out.write("\t  \t            location:'w',\r\n");
      out.write("\t  \t            fontSize: 15\r\n");
      out.write("\t  \t        },\r\n");
      out.write("\t  \t      \tseriesColors:['#7B93B4', '#F6A0AA', '#7BBD9D', '#DDF39E', '#FFDAA6']\r\n");
      out.write("\t  \t    }); \r\n");
      out.write("    \t  agePlot4 = $.jqplot('age40Plot', [age40], {\r\n");
      out.write("\t  \t        gridPadding: {top:0, bottom:38, left:0, right:0},\r\n");
      out.write("\t  \t      seriesDefaults:{\r\n");
      out.write("\t  \t            renderer:$.jqplot.PieRenderer, \r\n");
      out.write("\t  \t            trendline:{ show:false }, \r\n");
      out.write("\t  \t            rendererOptions: { padding: 8, showDataLabels: true, sliceMargin:6, dataLabelFontSize:50 },\r\n");
      out.write("\t  \t        },\r\n");
      out.write("\t  \t        legend:{\r\n");
      out.write("\t  \t            show:true, \r\n");
      out.write("\t  \t            location:'w',\r\n");
      out.write("\t  \t            fontSize: 15\r\n");
      out.write("\t  \t        },\r\n");
      out.write("\t  \t      \tseriesColors:['#7B93B4', '#F6A0AA', '#7BBD9D', '#DDF39E', '#FFDAA6']\r\n");
      out.write("\t  \t    }); \r\n");
      out.write("    \t  \r\n");
      out.write("    \t  agePlot5 = $.jqplot('ageEtcPlot', [ageEtc], {\r\n");
      out.write("\t  \t        gridPadding: {top:0, bottom:38, left:0, right:0},\r\n");
      out.write("\t  \t      seriesDefaults:{\r\n");
      out.write("\t  \t            renderer:$.jqplot.PieRenderer, \r\n");
      out.write("\t  \t            trendline:{ show:false }, \r\n");
      out.write("\t  \t            rendererOptions: { padding: 8, showDataLabels: true, sliceMargin:6, dataLabelFontSize:50 },\r\n");
      out.write("\t  \t        },\r\n");
      out.write("\t  \t        legend:{\r\n");
      out.write("\t  \t            show:true, \r\n");
      out.write("\t  \t            location:'w',\r\n");
      out.write("\t  \t            fontSize: 15\r\n");
      out.write("\t  \t        },\r\n");
      out.write("\t  \t      \tseriesColors:['#7B93B4', '#F6A0AA', '#7BBD9D', '#DDF39E', '#FFDAA6']\r\n");
      out.write("\t  \t    });\r\n");
      out.write("\t      });\r\n");
      out.write("      \r\n");
      out.write("      $(document).ready(function(){\r\n");
      out.write("    \t  \r\n");
      out.write("    \t  var male = [];\r\n");
      out.write("    \t  var female = [];\r\n");
      out.write("    \t  \r\n");
      out.write("    \t  ");
      if (_jspx_meth_c_005fforEach_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("// sortArr(male);\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  ");
      if (_jspx_meth_c_005fforEach_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t // sortArr(female);\r\n");
      out.write("    \t  \r\n");
      out.write("    \t  genderPlot1 = $.jqplot('malePlot', [male], {\r\n");
      out.write("\t  \t        gridPadding: {top:0, bottom:38, left:0, right:0},\r\n");
      out.write("\t  \t      seriesDefaults:{\r\n");
      out.write("\t  \t            renderer:$.jqplot.PieRenderer, \r\n");
      out.write("\t  \t            trendline:{ show:false }, \r\n");
      out.write("\t  \t            rendererOptions: { padding: 8, showDataLabels: true, sliceMargin:6, dataLabelFontSize:50 },\r\n");
      out.write("\t  \t        },\r\n");
      out.write("\t  \t        legend:{\r\n");
      out.write("\t  \t            show:true, \r\n");
      out.write("\t  \t            location:'w',\r\n");
      out.write("\t  \t            fontSize: 15\r\n");
      out.write("\t  \t        },\r\n");
      out.write("  \t        seriesColors:['#7B93B4', '#F6A0AA', '#7BBD9D', '#DDF39E', '#FFDAA6']       \r\n");
      out.write("\t  \t    });\r\n");
      out.write("\t      genderPlot2 = $.jqplot('femalePlot', [female], {\r\n");
      out.write("\t\t        gridPadding: {top:0, bottom:38, left:0, right:0},\r\n");
      out.write("\t\t        seriesDefaults:{\r\n");
      out.write("\t  \t            renderer:$.jqplot.PieRenderer, \r\n");
      out.write("\t  \t            trendline:{ show:false }, \r\n");
      out.write("\t  \t            rendererOptions: { padding: 8, showDataLabels: true, sliceMargin:6, dataLabelFontSize:50 },\r\n");
      out.write("\t  \t        },\r\n");
      out.write("\t  \t        legend:{\r\n");
      out.write("\t  \t            show:true, \r\n");
      out.write("\t  \t            location:'w',\r\n");
      out.write("\t  \t            fontSize: 15\r\n");
      out.write("\t  \t        },\r\n");
      out.write("    \t        seriesColors:['#7B93B4', '#F6A0AA', '#7BBD9D', '#DDF39E', '#FFDAA6']       \r\n");
      out.write("\t\t    });\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("      $(document).ready(function(){\r\n");
      out.write("    \t  \r\n");
      out.write("    \t  var coffee = []\r\n");
      out.write("    \t  var beverage = []\r\n");
      out.write("    \t  var dessert = []\r\n");
      out.write("    \t  \r\n");
      out.write("    \t  ");
      if (_jspx_meth_c_005fforEach_005f8(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t  //sortArr(coffee);\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  ");
      if (_jspx_meth_c_005fforEach_005f9(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t // sortArr(beverage);\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  ");
      if (_jspx_meth_c_005fforEach_005f10(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t // sortArr(dessert);\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  console.log(coffee);\r\n");
      out.write("\t\t  console.log(beverage);\r\n");
      out.write("\t\t  console.log(dessert);\r\n");
      out.write("    \t  \r\n");
      out.write("    \t  menuPlot1 = $.jqplot('coffeePlot', [coffee], {\r\n");
      out.write("\t  \t        gridPadding: {top:0, bottom:38, left:0, right:0},\r\n");
      out.write("\t  \t        seriesDefaults:{\r\n");
      out.write("\t  \t            renderer:$.jqplot.PieRenderer, \r\n");
      out.write("\t  \t            trendline:{ show:false }, \r\n");
      out.write("\t  \t            rendererOptions: { padding: 8, showDataLabels: true, sliceMargin:6, dataLabelFontSize:50 },\r\n");
      out.write("\t  \t        },\r\n");
      out.write("\t  \t        legend:{\r\n");
      out.write("\t  \t            show:true, \r\n");
      out.write("\t  \t            location:'w',\r\n");
      out.write("\t  \t            fontSize: 15\r\n");
      out.write("\t  \t        },\r\n");
      out.write("\t  \t        seriesColors:['#7B93B4', '#F6A0AA', '#7BBD9D', '#DDF39E', '#FFDAA6']\r\n");
      out.write("\t  \t       \r\n");
      out.write("\t  \t    });\r\n");
      out.write("\t      menuPlot2 = $.jqplot('beveragePlot', [beverage], {\r\n");
      out.write("\t\t        gridPadding: {top:0, bottom:38, left:0, right:0},\r\n");
      out.write("\t\t        seriesDefaults:{\r\n");
      out.write("\t\t            renderer:$.jqplot.PieRenderer, \r\n");
      out.write("\t\t            trendline:{ show:false }, \r\n");
      out.write("\t\t            rendererOptions: { padding: 8, showDataLabels: true, sliceMargin:6 }\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        legend:{\r\n");
      out.write("\t\t            show:true, \r\n");
      out.write("\t\t            location:'w',\r\n");
      out.write("\t\t            fontSize: 15\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t  \t        seriesColors:['#7B93B4', '#F6A0AA', '#7BBD9D', '#DDF39E', '#FFDAA6'] \r\n");
      out.write("\t\t    });\r\n");
      out.write("\t      menuPlot3 = $.jqplot('dessertPlot', [dessert], {\r\n");
      out.write("\t\t        gridPadding: {top:0, bottom:38, left:0, right:0},\r\n");
      out.write("\t\t        seriesDefaults:{\r\n");
      out.write("\t\t            renderer:$.jqplot.PieRenderer, \r\n");
      out.write("\t\t            trendline:{ show:false }, \r\n");
      out.write("\t\t            rendererOptions: { padding: 8, showDataLabels: true, sliceMargin:6 }\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        legend:{\r\n");
      out.write("\t\t            show:true, \r\n");
      out.write("\t\t            location:'w',\r\n");
      out.write("\t\t            fontSize: 15\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t  \t        seriesColors:['#7B93B4', '#F6A0AA', '#7BBD9D', '#DDF39E', '#FFDAA6']     \r\n");
      out.write("\t\t    });\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("      $(document).ready(function(){\r\n");
      out.write("          $('a[href=\"#month\"]').tab('show');\r\n");
      out.write("          $('a[href=\"#age\"]').tab('show');\r\n");
      out.write("    \t  $('a[href=\"#age10\"]').tab('show');\r\n");
      out.write("    \t  $('a[href=\"#age20\"]').tab('show');\r\n");
      out.write("    \t  $('a[href=\"#age30\"]').tab('show');\r\n");
      out.write("    \t  $('a[href=\"#age40\"]').tab('show');\r\n");
      out.write("    \t  $('a[href=\"#ageEtc\"]').tab('show');\r\n");
      out.write("          $('a[href=\"#age10\"]').tab('show');\r\n");
      out.write("    \t  $('a[href=\"#gender\"]').tab('show');\r\n");
      out.write("    \t  $('a[href=\"#male\"]').tab('show');\r\n");
      out.write("    \t  $('a[href=\"#female\"]').tab('show');\r\n");
      out.write("    \t  $('a[href=\"#male\"]').tab('show');\r\n");
      out.write("    \t  $('a[href=\"#menu\"]').tab('show');\r\n");
      out.write("    \t  $('a[href=\"#coffee\"]').tab('show');\r\n");
      out.write("    \t  $('a[href=\"#beverage\"]').tab('show');\r\n");
      out.write("    \t  $('a[href=\"#dessert\"]').tab('show');\r\n");
      out.write("    \t  $('a[href=\"#coffee\"]').tab('show');\r\n");
      out.write("\r\n");
      out.write("          $('a[href=\"#month\"]').tab('show');\r\n");
      out.write("          \r\n");
      out.write("          /*var activeTab = \"#month\";\r\n");
      out.write("          $('a[data-toggle=\"tab\"]').on('shown.bs.tab', function (e){\r\n");
      out.write("        \t  activeTab = $(e.target).attr('href');\r\n");
      out.write("          });*/\r\n");
      out.write("          \r\n");
      out.write("          /*$(window).resize(function(){\r\n");
      out.write("        \t  var storeTab = \"a[href=\"+ activeTab + \"]\";\r\n");
      out.write("        \t  $('a[href=\"#month\"]').tab('show');\r\n");
      out.write("        \t  plot1.replot( { resetAxes: true } );\r\n");
      out.write("        \t  \r\n");
      out.write("        \t  $('a[href=\"#age\"]').tab('show');\r\n");
      out.write("        \t  $('a[href=\"#age10\"]').tab('show');\r\n");
      out.write("        \t  agePlot1.replot( { resetAxes: true } );\r\n");
      out.write("        \t  $('a[href=\"#age20\"]').tab('show');\r\n");
      out.write("        \t  agePlot2.replot( { resetAxes: true } );\r\n");
      out.write("        \t  $('a[href=\"#age30\"]').tab('show');\r\n");
      out.write("        \t  agePlot3.replot( { resetAxes: true } );\r\n");
      out.write("        \t  $('a[href=\"#age40\"]').tab('show');\r\n");
      out.write("        \t  agePlot4.replot( { resetAxes: true } );\r\n");
      out.write("        \t  $('a[href=\"#ageEtc\"]').tab('show');\r\n");
      out.write("        \t  agePlot5.replot( { resetAxes: true } );\r\n");
      out.write("        \t  \r\n");
      out.write("        \t  $('a[href=\"#gender\"]').tab('show');\r\n");
      out.write("        \t  $('a[href=\"#male\"]').tab('show');\r\n");
      out.write("        \t  genderPlot1.replot( { resetAxes: true } );\r\n");
      out.write("        \t  $('a[href=\"#female\"]').tab('show');\r\n");
      out.write("        \t  genderPlot2.replot( { resetAxes: true } );\r\n");
      out.write("        \t  \r\n");
      out.write("        \t  $('a[href=\"#menu\"]').tab('show');\r\n");
      out.write("        \t  $('a[href=\"#coffee\"]').tab('show');\r\n");
      out.write("        \t  menuPlot1.replot( { resetAxes: true } );\r\n");
      out.write("        \t  $('a[href=\"#beverage\"]').tab('show');\r\n");
      out.write("        \t  menuPlot2.replot( { resetAxes: true } );\r\n");
      out.write("        \t  $('a[href=\"#dessert\"]').tab('show');\r\n");
      out.write("        \t  menuPlot3.replot( { resetAxes: true } );\r\n");
      out.write("        \t  // We've resized all, let's go back to the active tab.\r\n");
      out.write("        \t  $(''+storeTab).tab('show');\r\n");
      out.write("          });*/\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("      function sortArr(arr){\r\n");
      out.write("    \t  var tmp;\r\n");
      out.write("    \t  for(var i = 0; i < arr.length; i++){\r\n");
      out.write("    \t\t  tmp = arr[i];\r\n");
      out.write("    \t\t  console.log(tmp);\r\n");
      out.write("    \t\t  if(tmp[0] == \"기타\"){\r\n");
      out.write("    \t\t\t  arr.splice(i, 1);\r\n");
      out.write("    \t\t\t  break;\r\n");
      out.write("    \t\t  }\r\n");
      out.write("    \t  }\r\n");
      out.write("    \t  arr.push(tmp);\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/manProfit.jsp(195,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("row");
      // /WEB-INF/views/manProfit.jsp(195,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/manProfit.jsp(195,8) '${totalProfit}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${totalProfit}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\tdata1.push('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');\r\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/manProfit.jsp(246,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("row");
      // /WEB-INF/views/manProfit.jsp(246,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/manProfit.jsp(246,7) '${age10Map}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${age10Map}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t  \t  \tvar tmp = [];\r\n");
            out.write("\t  \t  \ttmp.push('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.key}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');\r\n");
            out.write("\t  \t  \ttmp.push(parseInt('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'));\r\n");
            out.write("\t  \t  \tage10.push(tmp);\r\n");
            out.write("\t\t  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /WEB-INF/views/manProfit.jsp(255,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("row");
      // /WEB-INF/views/manProfit.jsp(255,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/manProfit.jsp(255,4) '${age20Map}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${age20Map}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t  \t  \tvar tmp = [];\r\n");
            out.write("\t  \t  \ttmp.push('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.key}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');\r\n");
            out.write("\t  \t  \ttmp.push(parseInt('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'));\r\n");
            out.write("\t  \t  \tage20.push(tmp);\r\n");
            out.write("\t\t  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f3_reused = false;
    try {
      _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f3.setParent(null);
      // /WEB-INF/views/manProfit.jsp(264,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setVar("row");
      // /WEB-INF/views/manProfit.jsp(264,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/manProfit.jsp(264,4) '${age30Map}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${age30Map}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
        if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t  \t  \tvar tmp = [];\r\n");
            out.write("\t  \t  \ttmp.push('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.key}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');\r\n");
            out.write("\t  \t  \ttmp.push(parseInt('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'));\r\n");
            out.write("\t  \t  \tage30.push(tmp);\r\n");
            out.write("\t\t  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
      _jspx_th_c_005fforEach_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f4 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f4_reused = false;
    try {
      _jspx_th_c_005fforEach_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f4.setParent(null);
      // /WEB-INF/views/manProfit.jsp(273,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setVar("row");
      // /WEB-INF/views/manProfit.jsp(273,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/manProfit.jsp(273,4) '${age40Map}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${age40Map}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f4 = _jspx_th_c_005fforEach_005f4.doStartTag();
        if (_jspx_eval_c_005fforEach_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t  \t  \tvar tmp = [];\r\n");
            out.write("\t  \t  \ttmp.push('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.key}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');\r\n");
            out.write("\t  \t  \ttmp.push(parseInt('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'));\r\n");
            out.write("\t  \t  \tage40.push(tmp);\r\n");
            out.write("\t\t  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f4.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f4);
      _jspx_th_c_005fforEach_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f5 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f5_reused = false;
    try {
      _jspx_th_c_005fforEach_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f5.setParent(null);
      // /WEB-INF/views/manProfit.jsp(282,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f5.setVar("row");
      // /WEB-INF/views/manProfit.jsp(282,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f5.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/manProfit.jsp(282,4) '${ageEtcMap}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ageEtcMap}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f5 = _jspx_th_c_005fforEach_005f5.doStartTag();
        if (_jspx_eval_c_005fforEach_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t  \t  \tvar tmp = [];\r\n");
            out.write("\t  \t  \ttmp.push('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.key}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');\r\n");
            out.write("\t  \t  \ttmp.push(parseInt('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'));\r\n");
            out.write("\t  \t  \tageEtc.push(tmp);\r\n");
            out.write("\t\t  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f5.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f5.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f5);
      _jspx_th_c_005fforEach_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f6 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f6_reused = false;
    try {
      _jspx_th_c_005fforEach_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f6.setParent(null);
      // /WEB-INF/views/manProfit.jsp(371,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f6.setVar("row");
      // /WEB-INF/views/manProfit.jsp(371,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f6.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/manProfit.jsp(371,7) '${maleMap}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${maleMap}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f6 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f6 = _jspx_th_c_005fforEach_005f6.doStartTag();
        if (_jspx_eval_c_005fforEach_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t  \t  \tvar tmp = [];\r\n");
            out.write("\t  \t  \ttmp.push('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.key}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');\r\n");
            out.write("\t  \t  \ttmp.push(parseInt('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'));\r\n");
            out.write("\t  \t  \tmale.push(tmp);\r\n");
            out.write("\t\t  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f6.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f6[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f6.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f6.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f6);
      _jspx_th_c_005fforEach_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f7 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f7_reused = false;
    try {
      _jspx_th_c_005fforEach_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f7.setParent(null);
      // /WEB-INF/views/manProfit.jsp(379,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f7.setVar("row");
      // /WEB-INF/views/manProfit.jsp(379,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f7.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/manProfit.jsp(379,4) '${femaleMap}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${femaleMap}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f7 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f7 = _jspx_th_c_005fforEach_005f7.doStartTag();
        if (_jspx_eval_c_005fforEach_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t  \t  \tvar tmp = [];\r\n");
            out.write("\t  \t  \ttmp.push('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.key}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');\r\n");
            out.write("\t  \t  \ttmp.push(parseInt('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'));\r\n");
            out.write("\t  \t  \tfemale.push(tmp);\r\n");
            out.write("\t\t  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f7.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f7[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f7.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f7.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f7);
      _jspx_th_c_005fforEach_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f8 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f8_reused = false;
    try {
      _jspx_th_c_005fforEach_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f8.setParent(null);
      // /WEB-INF/views/manProfit.jsp(423,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f8.setVar("row");
      // /WEB-INF/views/manProfit.jsp(423,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f8.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/manProfit.jsp(423,7) '${coffeeMap}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${coffeeMap}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f8 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f8 = _jspx_th_c_005fforEach_005f8.doStartTag();
        if (_jspx_eval_c_005fforEach_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("    \t  \tvar tmp = [];\r\n");
            out.write("    \t  \ttmp.push('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.key}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');\r\n");
            out.write("    \t  \ttmp.push(parseInt('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'));\r\n");
            out.write("    \t  \tcoffee.push(tmp);\r\n");
            out.write("\t\t  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f8.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f8[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f8.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f8.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f8);
      _jspx_th_c_005fforEach_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f8, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f9 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f9_reused = false;
    try {
      _jspx_th_c_005fforEach_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f9.setParent(null);
      // /WEB-INF/views/manProfit.jsp(431,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f9.setVar("row");
      // /WEB-INF/views/manProfit.jsp(431,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f9.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/manProfit.jsp(431,4) '${beverageMap}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${beverageMap}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f9 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f9 = _jspx_th_c_005fforEach_005f9.doStartTag();
        if (_jspx_eval_c_005fforEach_005f9 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t  \t  \tvar tmp = [];\r\n");
            out.write("\t  \t  \ttmp.push('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.key}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');\r\n");
            out.write("\t  \t  \ttmp.push(parseInt('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'));\r\n");
            out.write("\t  \t  beverage.push(tmp);\r\n");
            out.write("\t\t  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f9.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f9[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f9.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f9.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f9);
      _jspx_th_c_005fforEach_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f9, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f10 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f10_reused = false;
    try {
      _jspx_th_c_005fforEach_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f10.setParent(null);
      // /WEB-INF/views/manProfit.jsp(439,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f10.setVar("row");
      // /WEB-INF/views/manProfit.jsp(439,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f10.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/manProfit.jsp(439,4) '${dessertMap}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${dessertMap}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f10 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f10 = _jspx_th_c_005fforEach_005f10.doStartTag();
        if (_jspx_eval_c_005fforEach_005f10 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t  \t  \tvar tmp = [];\r\n");
            out.write("\t  \t  \ttmp.push('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.key}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');\r\n");
            out.write("\t  \t  \ttmp.push(parseInt('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'));\r\n");
            out.write("\t  \t  dessert.push(tmp);\r\n");
            out.write("\t\t  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f10.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f10[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f10.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f10.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f10);
      _jspx_th_c_005fforEach_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f10, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f10_reused);
    }
    return false;
  }
}
