/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2017-12-16 17:26:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class manSeat_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/workspace/apache-tomcat-9.0.0.M26/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("file:/E:/workspace/apache-tomcat-9.0.0.M26/lib/jstl-1.2.jar", Long.valueOf(1504193458445L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset = \"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        <meta name=\"description\" content=\"\">\r\n");
      out.write("        <meta name=\"author\" content=\"\">\r\n");
      out.write("        <title>OTO CAFE</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/dashboard.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/custom.css\">\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("    \t<nav class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("          <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">\r\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"#\">OTO CAFE</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("          <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("            <li><a href=\"manOrder\">주문목록</a></li>\r\n");
      out.write("            <li><a href=\"manList\">상품리스트</a></li>\r\n");
      out.write("            <li><a href=\"manSeat\">좌석관리</a></li>\r\n");
      out.write("            <li><a href=\"manUser\">회원관리</a></li>\r\n");
      out.write("            <li><a href=\"manStock\">재고관리</a></li>\r\n");
      out.write("            <li><a href=\"manProfit\">판매실적</a></li>\r\n");
      out.write("            <li><a href=\"/jspweb/\">로그아웃</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-sm-3 col-md-2 sidebar\">\r\n");
      out.write("          <ul class=\"nav nav-sidebar form-left-nav\">\r\n");
      out.write("            <li><a href=\"manOrder\">주문목록</a></li>\r\n");
      out.write("            <li><a href=\"manList\">상품리스트</a></li>\r\n");
      out.write("            <li class=\"active\"><a href=\"manSeat\">좌석관리<span class=\"sr-only\">(current)</span></a></li>\r\n");
      out.write("            <li><a href=\"manUser\">회원관리</a></li>\r\n");
      out.write("            <li><a href=\"manStock\">재고관리</a></li>\r\n");
      out.write("            <li><a href=\"manProfit\">판매실적</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main\">\r\n");
      out.write("          <image class=\"img-responsive center-block img-rounded\" src = \"images/main_banner.jpg\">\r\n");
      out.write("            <div class=\"form-subject\">\r\n");
      out.write("               \t좌석관리\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr class=\"form-hr\">\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"table-responsive\">\r\n");
      out.write("            <table class=\"table table-striped\">\r\n");
      out.write("              <thead class=\"form-thead\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td class=\"counter\">\r\n");
      out.write("                    <button class=\"btn btn-default manBtn\" disabled=\"true\">카운터</button>\r\n");
      out.write("                  </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </thead>\r\n");
      out.write("              <tbody>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td class=\"seat\">\r\n");
      out.write("                    <button type=\"button\" id=\"1\" name=\"1\" value=\"1\" class=\"btn btn-default\" onclick=\"seatClick(this);\">1</button>\r\n");
      out.write("                    <button type=\"button\" id=\"2\" name=\"2\" value=\"2\" class=\"btn btn-default\" onclick=\"seatClick(this);\">2</button>\r\n");
      out.write("                    <div class=\"seat-interval\"></div>\r\n");
      out.write("                    <button type=\"button\" id=\"3\" name=\"3\" value=\"3\" class=\"btn btn-default\" onclick=\"seatClick(this);\">3</button>\r\n");
      out.write("                    <button type=\"button\" id=\"4\" name=\"4\" value=\"4\" class=\"btn btn-default\" onclick=\"seatClick(this);\">4</button>\r\n");
      out.write("                    <div class=\"seat-interval\"></div>\r\n");
      out.write("                    <button type=\"button\" id=\"5\" name=\"5\" value=\"5\" class=\"btn btn-default\" onclick=\"seatClick(this);\">5</button>\r\n");
      out.write("                    <button type=\"button\" id=\"6\" name=\"6\" value=\"6\" class=\"btn btn-default\" onclick=\"seatClick(this);\">6</button>\r\n");
      out.write("                    <div class=\"seat-interval\"></div>\r\n");
      out.write("                    <button type=\"button\" id=\"7\" name=\"7\" value=\"7\" class=\"btn btn-default\" onclick=\"seatClick(this);\">7</button>\r\n");
      out.write("                    <button type=\"button\" id=\"8\" name=\"8\" value=\"8\" class=\"btn btn-default\" onclick=\"seatClick(this);\">8</button>\r\n");
      out.write("                  </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td class=\"seat\">\r\n");
      out.write("                      <button type=\"button\" id=\"9\" name=\"9\" value=\"9\" class=\"btn btn-default\" onclick=\"seatClick(this);\">9</button>\r\n");
      out.write("                      <button type=\"button\" id=\"10\" name=\"10\" value=\"10\" class=\"btn btn-default\" onclick=\"seatClick(this);\">10</button>\r\n");
      out.write("                      <div class=\"seat-interval\"></div>\r\n");
      out.write("                      <button type=\"button\" id=\"11\" name=\"11\" value=\"11\" class=\"btn btn-default\" onclick=\"seatClick(this);\">11</button>\r\n");
      out.write("                      <button type=\"button\" id=\"12\" name=\"12\" value=\"12\" class=\"btn btn-default\" onclick=\"seatClick(this);\">12</button>\r\n");
      out.write("                      <div class=\"seat-interval\"></div>\r\n");
      out.write("                      <button type=\"button\" id=\"13\" name=\"13\" value=\"13\" class=\"btn btn-default\" onclick=\"seatClick(this);\">13</button>\r\n");
      out.write("                      <button type=\"button\" id=\"14\" name=\"14\" value=\"14\" class=\"btn btn-default\" onclick=\"seatClick(this);\">14</button>\r\n");
      out.write("                      <div class=\"seat-interval\"></div>\r\n");
      out.write("                      <button type=\"button\" id=\"15\" name=\"15\" value=\"15\" class=\"btn btn-default\" onclick=\"seatClick(this);\">15</button>\r\n");
      out.write("                      <button type=\"button\" id=\"16\" name=\"16\" value=\"16\" class=\"btn btn-default\" onclick=\"seatClick(this);\">16</button>\r\n");
      out.write("                  </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td class=\"seat\">\r\n");
      out.write("                      <button type=\"button\" id=\"17\" name=\"17\" value=\"17\" class=\"btn btn-default\" onclick=\"seatClick(this);\">17</button>\r\n");
      out.write("                      <button type=\"button\" id=\"18\" name=\"18\" value=\"18\" class=\"btn btn-default\" onclick=\"seatClick(this);\">18</button>\r\n");
      out.write("                      <div class=\"seat-interval\"></div>\r\n");
      out.write("                      <button type=\"button\" id=\"19\" name=\"19\" value=\"19\" class=\"btn btn-default\" onclick=\"seatClick(this);\">19</button>\r\n");
      out.write("                      <button type=\"button\" id=\"20\" name=\"20\" value=\"20\" class=\"btn btn-default\" onclick=\"seatClick(this);\">20</button>\r\n");
      out.write("                      <div class=\"seat-interval\"></div>\r\n");
      out.write("                      <button type=\"button\" id=\"21\" name=\"21\" value=\"21\" class=\"btn btn-default\" onclick=\"seatClick(this);\">21</button>\r\n");
      out.write("                      <button type=\"button\" id=\"22\" name=\"22\" value=\"22\" class=\"btn btn-default\" onclick=\"seatClick(this);\">22</button>\r\n");
      out.write("                      <div class=\"seat-interval\"></div>\r\n");
      out.write("                      <button type=\"button\" id=\"23\" name=\"23\" value=\"23\" class=\"btn btn-default\" onclick=\"seatClick(this);\">23</button>\r\n");
      out.write("                      <button type=\"button\" id=\"24\" name=\"24\" value=\"24\" class=\"btn btn-default\" onclick=\"seatClick(this);\">24</button>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td class=\"seat\">\r\n");
      out.write("                      <button type=\"button\" id=\"25\" name=\"25\" value=\"25\" class=\"btn btn-default\" onclick=\"seatClick(this);\">25</button>\r\n");
      out.write("                      <button type=\"button\" id=\"26\" name=\"26\" value=\"26\" class=\"btn btn-default\" onclick=\"seatClick(this);\">26</button>\r\n");
      out.write("                      <div class=\"seat-interval\"></div>\r\n");
      out.write("                      <button type=\"button\" id=\"27\" name=\"27\" value=\"27\" class=\"btn btn-default\" onclick=\"seatClick(this);\">27</button>\r\n");
      out.write("                      <button type=\"button\" id=\"28\" name=\"28\" value=\"28\" class=\"btn btn-default\" onclick=\"seatClick(this);\">28</button>\r\n");
      out.write("                      <div class=\"seat-interval\"></div>\r\n");
      out.write("                      <button type=\"button\" id=\"29\" name=\"29\" value=\"29\" class=\"btn btn-default\" onclick=\"seatClick(this);\">29</button>\r\n");
      out.write("                      <button type=\"button\" id=\"30\" name=\"30\" value=\"30\" class=\"btn btn-default\" onclick=\"seatClick(this);\">30</button>\r\n");
      out.write("                      <div class=\"seat-interval\"></div>\r\n");
      out.write("                      <button type=\"button\" id=\"31\" name=\"31\" value=\"31\" class=\"btn btn-default\" onclick=\"seatClick(this);\">31</button>\r\n");
      out.write("                      <button type=\"button\" id=\"32\" name=\"32\" value=\"32\" class=\"btn btn-default\" onclick=\"seatClick(this);\">32</button>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"modal fade bs-example-modal-sm\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t  <div class=\"modal-dialog modal-sm\">\r\n");
      out.write("\t    <div class=\"modal-content\">\r\n");
      out.write("\t      <div class=\"modal-header\">\r\n");
      out.write("\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("\t        <h4 class=\"modal-title\" id=\"myModalLabel\">좌석 취소</h4>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t      <div class=\"modal-body\">\r\n");
      out.write("\t        \t선택하신 좌석을 취소하겠습니까?\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t      <div class=\"modal-footer\">\r\n");
      out.write("\t        <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("\t        <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\" onclick=\"deleteSeat();\">확인</button>\r\n");
      out.write("\t        <input type=\"text\" id=\"tmpElm\" style=\"display:none;\" value=\"\">\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("    \r\n");
      out.write("        <script src= \"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("        \tvar seatCount = parseInt('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${seatCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("        \r\n");
      out.write("\t\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tsetInterval(checkInsert, 1000);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction seatClick(elm){\r\n");
      out.write("\t\t\t\tconsole.log(elm);\r\n");
      out.write("\t\t\t\tvar query = {num:$(elm).val()};\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"manSeat/insert\",\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tdata : query,\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\tif(data == 0){\r\n");
      out.write("\t\t\t\t\t\t\t$(elm).css(\"background-color\", \"#ddd\");\r\n");
      out.write("\t\t\t\t\t\t\t$(elm).attr('onclick', \"\");//.click(deleteSeatClick(elm));\r\n");
      out.write("\t\t\t\t\t\t\t$(elm).attr('onclick', \"deleteSeatClick(this)\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\tfunction deleteSeatClick(elm){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tmodalInit($(elm).attr('id'));\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#myModal').modal('show');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction modalInit(id){\r\n");
      out.write("\t\t\t\t$(\"#tmpElm\").val(id);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction deleteSeat(){\r\n");
      out.write("\t\t\t\tvar id = $(\"#tmpElm\").val();\r\n");
      out.write("\t\t\t\tconsole.log(id);\r\n");
      out.write("\t\t\t\tvar query = {num:$(\"#\"+id).val()};\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"manSeat/delete\",\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tdata : query,\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\tif(data == 0){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#\"+id).css(\"background-color\", \"#fff\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#\"+id).attr('onclick', \"\");//.click(seatClick(elm));\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#\"+id).attr('onclick', \"seatClick(this)\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction checkInsert(){\r\n");
      out.write("        \t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"manSeat/checkCount\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\tif(seatCount != data)\r\n");
      out.write("\t\t\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\t\r\n");
      out.write("        \t}\r\n");
      out.write("       \r\n");
      out.write("        </script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/manSeat.jsp(166,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("row");
      // /WEB-INF/views/manSeat.jsp(166,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/manSeat.jsp(166,4) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\tvar tmp = \"#\" + '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.seatNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("';\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\t\t$(tmp).attr('onclick', \"\");\r\n");
            out.write("\t\t\t\t$(tmp).attr('onclick', \"deleteSeatClick(this)\")\r\n");
            out.write("\t\t\t\t$(tmp).css(\"background-color\", \"#ddd\");\r\n");
            out.write("\t\t\t\t$(tmp).attr('disabled', false);\r\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
